/**
 * Produktkatalog — Platzhalterdaten.
 * Preise sind Beispielwerte und müssen von SERGIO final geprüft/angepasst werden.
 * Bilder stammen aus vorhandenem Instagram-Material und sollten bei Bedarf
 * durch professionelle Produktfotos (einheitlicher Hintergrund) ersetzt werden.
 */
const PRODUCTS = [
  {
    id: "ring-organic-gold",
    name: "Ring „Terra“ mit Goldfassung",
    category: "ringe",
    categoryLabel: "Ringe",
    price: 149,
    material: "925er Silber, geschmolzene Struktur, 585er Goldfassung",
    desc: "Handgeschmolzener Unikat-Ring mit organischer, roher Oberfläche und aufgesetzter Goldfassung.",
    img: "assets/img/ring-organic-gold.png",
    badge: "Unikat",
  },
  {
    id: "ring-organic-band",
    name: "Ring „Basalt“",
    category: "ringe",
    categoryLabel: "Ringe",
    price: 119,
    material: "925er Silber, geschmolzene Struktur",
    desc: "Breiter Silberring mit vulkanisch anmutender, individuell geschmolzener Textur — kein Ring gleicht dem anderen.",
    img: "assets/img/ring-organic-band.png",
    badge: "Unikat",
  },
  {
    id: "necklace-lariat-gold",
    name: "Kette „Lyra“ vergoldet",
    category: "halsketten",
    categoryLabel: "Halsketten",
    price: 79,
    material: "Edelstahl vergoldet, verstellbarer Lariat-Verschluss",
    desc: "Feine Ankerkette mit offenem Lariat-Verschluss zum flexiblen Einstellen der Länge.",
    img: "assets/img/necklace-lariat-gold.png",
  },
  {
    id: "necklace-lariat-silver",
    name: "Kette „Lyra“ Silber",
    category: "halsketten",
    categoryLabel: "Halsketten",
    price: 69,
    material: "Edelstahl, verstellbarer Lariat-Verschluss",
    desc: "Die zeitlose Silber-Variante unserer Lariat-Kette mit T-Stab-Anhänger.",
    img: "assets/img/necklace-lariat-silver.png",
  },
  {
    id: "necklace-black-beads",
    name: "Kette „Onyx“ mit Perlen",
    category: "halsketten",
    categoryLabel: "Halsketten",
    price: 59,
    material: "Edelstahl, Emaille-Perlen",
    desc: "Zarte Ankerkette mit schwarzen Emaille-Perlen — dezent und alltagstauglich.",
    img: "assets/img/necklace-black-beads.png",
  },
  {
    id: "bracelet-pearl-gold",
    name: "Armband „Perla“ Doppelreihe",
    category: "armbaender",
    categoryLabel: "Armbänder",
    price: 54,
    material: "Edelstahl vergoldet, Süßwasserperlen",
    desc: "Zwei kombinierte Kettenstile mit kleinen Perlen für einen lässigen Layering-Look.",
    img: "assets/img/bracelet-pearl-gold.png",
  },
  {
    id: "bracelet-black-beads",
    name: "Armband „Onyx“",
    category: "armbaender",
    categoryLabel: "Armbänder",
    price: 39,
    material: "Edelstahl, Emaille-Perlen",
    desc: "Das passende Armband zur Onyx-Kette — einzeln oder im Set.",
    img: "assets/img/bracelet-black-beads.png",
  },
  {
    id: "bracelet-gold-silver",
    name: "Armband „Duo“ Gold & Silber",
    category: "armbaender",
    categoryLabel: "Armbänder",
    price: 49,
    material: "Edelstahl, gold- und silberfarben",
    desc: "Zwei filigrane Ankerketten in unterschiedlichen Tönen, einzeln oder gestapelt tragbar.",
    img: "assets/img/bracelet-gold-silver-wrist.png",
  },
  {
    id: "chain-colorful-beads",
    name: "Armband „Sommer“ bunt",
    category: "armbaender",
    categoryLabel: "Armbänder",
    price: 42,
    material: "Vergoldeter Edelstahl, Emaille-Perlen",
    desc: "Fröhliche Farbvarianten in Pink, Blau und Weiß — auch als Fußkette erhältlich.",
    img: "assets/img/chains-colorful-rock.png",
  },
  {
    id: "anklet-pearl",
    name: "Fußkette „Bay“",
    category: "fussketten",
    categoryLabel: "Fußketten",
    price: 36,
    material: "Edelstahl, Süßwasserperlen, wasserfest",
    desc: "Salzwasser- und chlorbeständige Fußkette für den Sommer am Strand oder Pool.",
    img: "assets/img/hero-anklet-beach.png",
  },
  {
    id: "anklet-duo",
    name: "Fußketten-Set „Duo“",
    category: "fussketten",
    categoryLabel: "Fußketten",
    price: 58,
    material: "Edelstahl, 2er Set",
    desc: "Zwei fein aufeinander abgestimmte Fußketten im Set — einzeln oder zusammen getragen.",
    img: "assets/img/hero-anklets-beach2.png",
  },
  {
    id: "gutschein-50",
    name: "Geschenkgutschein",
    category: "gutscheine",
    categoryLabel: "Gutscheine",
    price: 50,
    material: "Wählbar: 25 € – 200 €, gültig für Schmuck &amp; Permanent-Termine",
    desc: "Der perfekte Gutschein für alle, die sich noch nicht entscheiden können — einlösbar im Shop und für Permanent-Schmuck-Termine.",
    img: "assets/img/gift-voucher.png",
    badge: "Beliebt",
  },
];
